// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package db

import (
	"context"
)

const countOpenAlerts = `-- name: CountOpenAlerts :one
SELECT COUNT(*) FROM alert_events
WHERE tenant_id = $1
  AND resolved_at IS NULL AND ignored_at IS NULL
`

func (q *Queries) CountOpenAlerts(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenAlerts, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :exec
INSERT INTO alert_events (id, tenant_id, level, type, campaign_id, campaign_name, message, details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAlertParams struct {
	ID           string  `json:"id"`
	TenantID     string  `json:"tenant_id"`
	Level        string  `json:"level"`
	Type         string  `json:"type"`
	CampaignID   *string `json:"campaign_id"`
	CampaignName *string `json:"campaign_name"`
	Message      string  `json:"message"`
	Details      []byte  `json:"details"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) error {
	_, err := q.db.Exec(ctx, createAlert,
		arg.ID,
		arg.TenantID,
		arg.Level,
		arg.Type,
		arg.CampaignID,
		arg.CampaignName,
		arg.Message,
		arg.Details,
	)
	return err
}

const ignoreAlert = `-- name: IgnoreAlert :exec
UPDATE alert_events SET ignored_at = NOW() WHERE id = $1
`

func (q *Queries) IgnoreAlert(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, ignoreAlert, id)
	return err
}

const listAlertHistory = `-- name: ListAlertHistory :many
SELECT id, tenant_id, level, type, campaign_id, campaign_name, message, details, resolved_at, ignored_at, created_at FROM alert_events
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListAlertHistoryParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListAlertHistory(ctx context.Context, arg ListAlertHistoryParams) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listAlertHistory, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertEvent
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Level,
			&i.Type,
			&i.CampaignID,
			&i.CampaignName,
			&i.Message,
			&i.Details,
			&i.ResolvedAt,
			&i.IgnoredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAlerts = `-- name: ListOpenAlerts :many
SELECT id, tenant_id, level, type, campaign_id, campaign_name, message, details, resolved_at, ignored_at, created_at FROM alert_events
WHERE tenant_id = $1
  AND resolved_at IS NULL AND ignored_at IS NULL
ORDER BY
    CASE level WHEN 'CRITICAL' THEN 0 ELSE 1 END,
    created_at DESC
`

func (q *Queries) ListOpenAlerts(ctx context.Context, tenantID string) ([]AlertEvent, error) {
	rows, err := q.db.Query(ctx, listOpenAlerts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertEvent
	for rows.Next() {
		var i AlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Level,
			&i.Type,
			&i.CampaignID,
			&i.CampaignName,
			&i.Message,
			&i.Details,
			&i.ResolvedAt,
			&i.IgnoredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :exec
UPDATE alert_events SET resolved_at = NOW() WHERE id = $1
`

func (q *Queries) ResolveAlert(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, resolveAlert, id)
	return err
}
