// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package db

import (
	"context"
	"encoding/json"
)

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getCampaignBySlug = `-- name: GetCampaignBySlug :one
SELECT id, tenant_id, slug, data, deployed_at, created_at, updated_at FROM campaigns WHERE tenant_id = $1 AND slug = $2 LIMIT 1
`

type GetCampaignBySlugParams struct {
	TenantID string `json:"tenant_id"`
	Slug     string `json:"slug"`
}

func (q *Queries) GetCampaignBySlug(ctx context.Context, arg GetCampaignBySlugParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignBySlug, arg.TenantID, arg.Slug)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Data,
		&i.DeployedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, tenant_id, slug, data, deployed_at, created_at, updated_at FROM campaigns WHERE tenant_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCampaigns(ctx context.Context, tenantID string) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaigns, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Data,
			&i.DeployedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCampaignDeployed = `-- name: MarkCampaignDeployed :exec
UPDATE campaigns SET deployed_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkCampaignDeployed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markCampaignDeployed, id)
	return err
}

const upsertCampaign = `-- name: UpsertCampaign :exec
INSERT INTO campaigns (id, tenant_id, slug, data)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, slug) DO UPDATE
SET data = EXCLUDED.data, updated_at = NOW()
`

type UpsertCampaignParams struct {
	ID       string          `json:"id"`
	TenantID string          `json:"tenant_id"`
	Slug     string          `json:"slug"`
	Data     json.RawMessage `json:"data"`
}

func (q *Queries) UpsertCampaign(ctx context.Context, arg UpsertCampaignParams) error {
	_, err := q.db.Exec(ctx, upsertCampaign,
		arg.ID,
		arg.TenantID,
		arg.Slug,
		arg.Data,
	)
	return err
}
