// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package db

import (
	"context"
)

const createIntegration = `-- name: CreateIntegration :exec
INSERT INTO integrations (id, name, provider, "group", oauth_client_id, oauth_client_secret,
    developer_token, login_customer_id, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateIntegrationParams struct {
	ID                string  `json:"id"`
	Name              string  `json:"name"`
	Provider          string  `json:"provider"`
	Group             string  `json:"group"`
	OauthClientID     *string `json:"oauth_client_id"`
	OauthClientSecret *string `json:"oauth_client_secret"`
	DeveloperToken    *string `json:"developer_token"`
	LoginCustomerID   *string `json:"login_customer_id"`
	Status            string  `json:"status"`
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) error {
	_, err := q.db.Exec(ctx, createIntegration,
		arg.ID,
		arg.Name,
		arg.Provider,
		arg.Group,
		arg.OauthClientID,
		arg.OauthClientSecret,
		arg.DeveloperToken,
		arg.LoginCustomerID,
		arg.Status,
	)
	return err
}

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations WHERE id = $1
`

func (q *Queries) DeleteIntegration(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteIntegration, id)
	return err
}

const deleteIntegrationTenants = `-- name: DeleteIntegrationTenants :exec
DELETE FROM integration_tenants WHERE integration_id = $1
`

func (q *Queries) DeleteIntegrationTenants(ctx context.Context, integrationID string) error {
	_, err := q.db.Exec(ctx, deleteIntegrationTenants, integrationID)
	return err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, name, provider, "group", oauth_client_id, oauth_client_secret, developer_token, login_customer_id, refresh_token, status, error_message, created_at, updated_at FROM integrations WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIntegrationByID(ctx context.Context, id string) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Group,
		&i.OauthClientID,
		&i.OauthClientSecret,
		&i.DeveloperToken,
		&i.LoginCustomerID,
		&i.RefreshToken,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationForTenant = `-- name: GetIntegrationForTenant :one
SELECT i.id, i.name, i.provider, i."group", i.oauth_client_id, i.oauth_client_secret, i.developer_token, i.login_customer_id, i.refresh_token, i.status, i.error_message, i.created_at, i.updated_at FROM integrations i
JOIN integration_tenants it ON it.integration_id = i.id
WHERE it.tenant_id = $1 AND i.provider = $2
  AND i.status = 'connected'
LIMIT 1
`

type GetIntegrationForTenantParams struct {
	TenantID string `json:"tenant_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetIntegrationForTenant(ctx context.Context, arg GetIntegrationForTenantParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationForTenant, arg.TenantID, arg.Provider)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Group,
		&i.OauthClientID,
		&i.OauthClientSecret,
		&i.DeveloperToken,
		&i.LoginCustomerID,
		&i.RefreshToken,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantsForIntegration = `-- name: GetTenantsForIntegration :many
SELECT tenant_id FROM integration_tenants WHERE integration_id = $1
`

func (q *Queries) GetTenantsForIntegration(ctx context.Context, integrationID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getTenantsForIntegration, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tenant_id string
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIntegrationTenant = `-- name: InsertIntegrationTenant :exec
INSERT INTO integration_tenants (integration_id, tenant_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertIntegrationTenantParams struct {
	IntegrationID string `json:"integration_id"`
	TenantID      string `json:"tenant_id"`
}

func (q *Queries) InsertIntegrationTenant(ctx context.Context, arg InsertIntegrationTenantParams) error {
	_, err := q.db.Exec(ctx, insertIntegrationTenant, arg.IntegrationID, arg.TenantID)
	return err
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, name, provider, "group", oauth_client_id, oauth_client_secret, developer_token, login_customer_id, refresh_token, status, error_message, created_at, updated_at FROM integrations ORDER BY name
`

func (q *Queries) ListIntegrations(ctx context.Context) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Integration
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Group,
			&i.OauthClientID,
			&i.OauthClientSecret,
			&i.DeveloperToken,
			&i.LoginCustomerID,
			&i.RefreshToken,
			&i.Status,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegration = `-- name: UpdateIntegration :exec
UPDATE integrations
SET name = $2, oauth_client_id = $3, oauth_client_secret = $4,
    developer_token = $5, login_customer_id = $6, refresh_token = $7,
    status = $8, error_message = $9, updated_at = NOW()
WHERE id = $1
`

type UpdateIntegrationParams struct {
	ID                string  `json:"id"`
	Name              string  `json:"name"`
	OauthClientID     *string `json:"oauth_client_id"`
	OauthClientSecret *string `json:"oauth_client_secret"`
	DeveloperToken    *string `json:"developer_token"`
	LoginCustomerID   *string `json:"login_customer_id"`
	RefreshToken      *string `json:"refresh_token"`
	Status            string  `json:"status"`
	ErrorMessage      *string `json:"error_message"`
}

func (q *Queries) UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) error {
	_, err := q.db.Exec(ctx, updateIntegration,
		arg.ID,
		arg.Name,
		arg.OauthClientID,
		arg.OauthClientSecret,
		arg.DeveloperToken,
		arg.LoginCustomerID,
		arg.RefreshToken,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}
