// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMetricsHistory = `-- name: GetMetricsHistory :many
SELECT id, tenant_id, date, campaign_id, campaign_name, impressions, clicks, cost_brl, conversions, cpa_brl, ctr, search_impression_share, created_at FROM daily_metrics
WHERE tenant_id = $1 AND date >= $2::date
ORDER BY date DESC
`

type GetMetricsHistoryParams struct {
	TenantID string      `json:"tenant_id"`
	Column2  pgtype.Date `json:"column_2"`
}

func (q *Queries) GetMetricsHistory(ctx context.Context, arg GetMetricsHistoryParams) ([]DailyMetric, error) {
	rows, err := q.db.Query(ctx, getMetricsHistory, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyMetric
	for rows.Next() {
		var i DailyMetric
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Date,
			&i.CampaignID,
			&i.CampaignName,
			&i.Impressions,
			&i.Clicks,
			&i.CostBrl,
			&i.Conversions,
			&i.CpaBrl,
			&i.Ctr,
			&i.SearchImpressionShare,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlySummary = `-- name: GetMonthlySummary :many
SELECT id, tenant_id, month, campaign_id, campaign_name, impressions, clicks, cost_brl, conversions, avg_cpa_brl, created_at FROM monthly_summary
WHERE tenant_id = $1
ORDER BY month DESC
LIMIT $2
`

type GetMonthlySummaryParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) GetMonthlySummary(ctx context.Context, arg GetMonthlySummaryParams) ([]MonthlySummary, error) {
	rows, err := q.db.Query(ctx, getMonthlySummary, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlySummary
	for rows.Next() {
		var i MonthlySummary
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Month,
			&i.CampaignID,
			&i.CampaignName,
			&i.Impressions,
			&i.Clicks,
			&i.CostBrl,
			&i.Conversions,
			&i.AvgCpaBrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDailyMetrics = `-- name: UpsertDailyMetrics :exec
INSERT INTO daily_metrics (id, tenant_id, date, campaign_id, campaign_name,
    impressions, clicks, cost_brl, conversions, cpa_brl, ctr, search_impression_share)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (tenant_id, date, campaign_id) DO UPDATE
SET impressions = EXCLUDED.impressions,
    clicks = EXCLUDED.clicks,
    cost_brl = EXCLUDED.cost_brl,
    conversions = EXCLUDED.conversions,
    cpa_brl = EXCLUDED.cpa_brl,
    ctr = EXCLUDED.ctr,
    search_impression_share = EXCLUDED.search_impression_share
`

type UpsertDailyMetricsParams struct {
	ID                    string         `json:"id"`
	TenantID              string         `json:"tenant_id"`
	Date                  pgtype.Date    `json:"date"`
	CampaignID            string         `json:"campaign_id"`
	CampaignName          string         `json:"campaign_name"`
	Impressions           int32          `json:"impressions"`
	Clicks                int32          `json:"clicks"`
	CostBrl               pgtype.Numeric `json:"cost_brl"`
	Conversions           pgtype.Numeric `json:"conversions"`
	CpaBrl                pgtype.Numeric `json:"cpa_brl"`
	Ctr                   pgtype.Numeric `json:"ctr"`
	SearchImpressionShare pgtype.Numeric `json:"search_impression_share"`
}

func (q *Queries) UpsertDailyMetrics(ctx context.Context, arg UpsertDailyMetricsParams) error {
	_, err := q.db.Exec(ctx, upsertDailyMetrics,
		arg.ID,
		arg.TenantID,
		arg.Date,
		arg.CampaignID,
		arg.CampaignName,
		arg.Impressions,
		arg.Clicks,
		arg.CostBrl,
		arg.Conversions,
		arg.CpaBrl,
		arg.Ctr,
		arg.SearchImpressionShare,
	)
	return err
}

const upsertMonthlySummary = `-- name: UpsertMonthlySummary :exec
INSERT INTO monthly_summary (id, tenant_id, month, campaign_id, campaign_name,
    impressions, clicks, cost_brl, conversions, avg_cpa_brl)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (tenant_id, month, campaign_id) DO UPDATE
SET impressions = EXCLUDED.impressions,
    clicks = EXCLUDED.clicks,
    cost_brl = EXCLUDED.cost_brl,
    conversions = EXCLUDED.conversions,
    avg_cpa_brl = EXCLUDED.avg_cpa_brl
`

type UpsertMonthlySummaryParams struct {
	ID           string         `json:"id"`
	TenantID     string         `json:"tenant_id"`
	Month        string         `json:"month"`
	CampaignID   string         `json:"campaign_id"`
	CampaignName string         `json:"campaign_name"`
	Impressions  int32          `json:"impressions"`
	Clicks       int32          `json:"clicks"`
	CostBrl      pgtype.Numeric `json:"cost_brl"`
	Conversions  pgtype.Numeric `json:"conversions"`
	AvgCpaBrl    pgtype.Numeric `json:"avg_cpa_brl"`
}

func (q *Queries) UpsertMonthlySummary(ctx context.Context, arg UpsertMonthlySummaryParams) error {
	_, err := q.db.Exec(ctx, upsertMonthlySummary,
		arg.ID,
		arg.TenantID,
		arg.Month,
		arg.CampaignID,
		arg.CampaignName,
		arg.Impressions,
		arg.Clicks,
		arg.CostBrl,
		arg.Conversions,
		arg.AvgCpaBrl,
	)
	return err
}
