// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO posts (id, tenant_id, status, title, content, hashtags, media_type,
    workflow, media_path, platforms, scheduled_date, scheduled_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreatePostParams struct {
	ID            string          `json:"id"`
	TenantID      string          `json:"tenant_id"`
	Status        string          `json:"status"`
	Title         *string         `json:"title"`
	Content       string          `json:"content"`
	Hashtags      json.RawMessage `json:"hashtags"`
	MediaType     *string         `json:"media_type"`
	Workflow      []byte          `json:"workflow"`
	MediaPath     *string         `json:"media_path"`
	Platforms     json.RawMessage `json:"platforms"`
	ScheduledDate *string         `json:"scheduled_date"`
	ScheduledTime *string         `json:"scheduled_time"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.Title,
		arg.Content,
		arg.Hashtags,
		arg.MediaType,
		arg.Workflow,
		arg.MediaPath,
		arg.Platforms,
		arg.ScheduledDate,
		arg.ScheduledTime,
	)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, tenant_id, status, title, content, hashtags, media_type, workflow, media_path, platforms, scheduled_date, scheduled_time, published_at, created_at, updated_at FROM posts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPostByID(ctx context.Context, id string) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.Title,
		&i.Content,
		&i.Hashtags,
		&i.MediaType,
		&i.Workflow,
		&i.MediaPath,
		&i.Platforms,
		&i.ScheduledDate,
		&i.ScheduledTime,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, tenant_id, status, title, content, hashtags, media_type, workflow, media_path, platforms, scheduled_date, scheduled_time, published_at, created_at, updated_at FROM posts WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPosts(ctx context.Context, tenantID string) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Status,
			&i.Title,
			&i.Content,
			&i.Hashtags,
			&i.MediaType,
			&i.Workflow,
			&i.MediaPath,
			&i.Platforms,
			&i.ScheduledDate,
			&i.ScheduledTime,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByStatus = `-- name: ListPostsByStatus :many
SELECT id, tenant_id, status, title, content, hashtags, media_type, workflow, media_path, platforms, scheduled_date, scheduled_time, published_at, created_at, updated_at FROM posts WHERE tenant_id = $1 AND status = $2
ORDER BY created_at DESC
`

type ListPostsByStatusParams struct {
	TenantID string `json:"tenant_id"`
	Status   string `json:"status"`
}

func (q *Queries) ListPostsByStatus(ctx context.Context, arg ListPostsByStatusParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPostsByStatus, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Status,
			&i.Title,
			&i.Content,
			&i.Hashtags,
			&i.MediaType,
			&i.Workflow,
			&i.MediaPath,
			&i.Platforms,
			&i.ScheduledDate,
			&i.ScheduledTime,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledPosts = `-- name: ListScheduledPosts :many
SELECT id, tenant_id, status, title, content, hashtags, media_type, workflow, media_path, platforms, scheduled_date, scheduled_time, published_at, created_at, updated_at FROM posts
WHERE tenant_id = $1 AND status = 'scheduled'
  AND scheduled_date IS NOT NULL
ORDER BY scheduled_date, scheduled_time
`

func (q *Queries) ListScheduledPosts(ctx context.Context, tenantID string) ([]Post, error) {
	rows, err := q.db.Query(ctx, listScheduledPosts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Status,
			&i.Title,
			&i.Content,
			&i.Hashtags,
			&i.MediaType,
			&i.Workflow,
			&i.MediaPath,
			&i.Platforms,
			&i.ScheduledDate,
			&i.ScheduledTime,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
UPDATE posts
SET title = $2, content = $3, hashtags = $4, media_type = $5,
    platforms = $6, scheduled_date = $7, scheduled_time = $8,
    workflow = $9, updated_at = NOW()
WHERE id = $1
`

type UpdatePostParams struct {
	ID            string          `json:"id"`
	Title         *string         `json:"title"`
	Content       string          `json:"content"`
	Hashtags      json.RawMessage `json:"hashtags"`
	MediaType     *string         `json:"media_type"`
	Platforms     json.RawMessage `json:"platforms"`
	ScheduledDate *string         `json:"scheduled_date"`
	ScheduledTime *string         `json:"scheduled_time"`
	Workflow      []byte          `json:"workflow"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.Exec(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Hashtags,
		arg.MediaType,
		arg.Platforms,
		arg.ScheduledDate,
		arg.ScheduledTime,
		arg.Workflow,
	)
	return err
}

const updatePostStatus = `-- name: UpdatePostStatus :exec
UPDATE posts SET status = $2, published_at = $3, updated_at = NOW() WHERE id = $1
`

type UpdatePostStatusParams struct {
	ID          string             `json:"id"`
	Status      string             `json:"status"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) error {
	_, err := q.db.Exec(ctx, updatePostStatus, arg.ID, arg.Status, arg.PublishedAt)
	return err
}
