// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_tenant_roles (user_id, tenant_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID   string `json:"user_id"`
	TenantID string `json:"tenant_id"`
	RoleID   string `json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.TenantID, arg.RoleID)
	return err
}

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (id, name, tenant_id) VALUES ($1, $2, $3)
`

type CreateRoleParams struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	TenantID *string `json:"tenant_id"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole, arg.ID, arg.Name, arg.TenantID)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID string) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getPermissionsForRole = `-- name: GetPermissionsForRole :many
SELECT p.name
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
`

func (q *Queries) GetPermissionsForRole(ctx context.Context, roleID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsForUser = `-- name: GetPermissionsForUser :many
SELECT p.name
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN user_tenant_roles utr ON utr.role_id = rp.role_id
WHERE utr.user_id = $1 AND utr.tenant_id = $2
`

type GetPermissionsForUserParams struct {
	UserID   string `json:"user_id"`
	TenantID string `json:"tenant_id"`
}

func (q *Queries) GetPermissionsForUser(ctx context.Context, arg GetPermissionsForUserParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissionsForUser, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, tenant_id FROM roles WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRoleByID(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.TenantID)
	return i, err
}

const getTenantsForUser = `-- name: GetTenantsForUser :many
SELECT DISTINCT tenant_id FROM user_tenant_roles WHERE user_id = $1
`

func (q *Queries) GetTenantsForUser(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getTenantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tenant_id string
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, name FROM permissions ORDER BY name
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, tenant_id FROM roles
WHERE tenant_id IS NULL OR tenant_id = $1
ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context, tenantID *string) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.TenantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_tenant_roles
WHERE user_id = $1 AND tenant_id = $2 AND role_id = $3
`

type RemoveRoleFromUserParams struct {
	UserID   string `json:"user_id"`
	TenantID string `json:"tenant_id"`
	RoleID   string `json:"role_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, arg.UserID, arg.TenantID, arg.RoleID)
	return err
}

const setRolePermissions = `-- name: SetRolePermissions :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT $1, id FROM permissions WHERE name = ANY($2::text[])
`

type SetRolePermissionsParams struct {
	RoleID  string   `json:"role_id"`
	Column2 []string `json:"column_2"`
}

func (q *Queries) SetRolePermissions(ctx context.Context, arg SetRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, setRolePermissions, arg.RoleID, arg.Column2)
	return err
}
