// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"
)

const createReport = `-- name: CreateReport :exec
INSERT INTO reports (id, tenant_id, slug, type, title, content)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateReportParams struct {
	ID       string  `json:"id"`
	TenantID string  `json:"tenant_id"`
	Slug     string  `json:"slug"`
	Type     string  `json:"type"`
	Title    *string `json:"title"`
	Content  string  `json:"content"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.Exec(ctx, createReport,
		arg.ID,
		arg.TenantID,
		arg.Slug,
		arg.Type,
		arg.Title,
		arg.Content,
	)
	return err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, tenant_id, slug, type, title, content, created_at FROM reports WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReportByID(ctx context.Context, id string) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getReportBySlug = `-- name: GetReportBySlug :one
SELECT id, tenant_id, slug, type, title, content, created_at FROM reports WHERE tenant_id = $1 AND slug = $2 LIMIT 1
`

type GetReportBySlugParams struct {
	TenantID string `json:"tenant_id"`
	Slug     string `json:"slug"`
}

func (q *Queries) GetReportBySlug(ctx context.Context, arg GetReportBySlugParams) (Report, error) {
	row := q.db.QueryRow(ctx, getReportBySlug, arg.TenantID, arg.Slug)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, tenant_id, slug, type, title, created_at
FROM reports WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ListReportsRow struct {
	ID        string    `json:"id"`
	TenantID  string    `json:"tenant_id"`
	Slug      string    `json:"slug"`
	Type      string    `json:"type"`
	Title     *string   `json:"title"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListReports(ctx context.Context, tenantID string) ([]ListReportsRow, error) {
	rows, err := q.db.Query(ctx, listReports, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReportsRow
	for rows.Next() {
		var i ListReportsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
