// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"
	"encoding/json"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name, language, niche, location, primary_persona, tone,
    instructions, hashtags, google_ads_id, ads_monitoring)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateTenantParams struct {
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	Language       string          `json:"language"`
	Niche          *string         `json:"niche"`
	Location       *string         `json:"location"`
	PrimaryPersona *string         `json:"primary_persona"`
	Tone           *string         `json:"tone"`
	Instructions   *string         `json:"instructions"`
	Hashtags       json.RawMessage `json:"hashtags"`
	GoogleAdsID    *string         `json:"google_ads_id"`
	AdsMonitoring  []byte          `json:"ads_monitoring"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Language,
		arg.Niche,
		arg.Location,
		arg.PrimaryPersona,
		arg.Tone,
		arg.Instructions,
		arg.Hashtags,
		arg.GoogleAdsID,
		arg.AdsMonitoring,
	)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, language, niche, location, primary_persona, tone, instructions, hashtags, google_ads_id, ads_monitoring, created_at, updated_at FROM tenants WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Language,
		&i.Niche,
		&i.Location,
		&i.PrimaryPersona,
		&i.Tone,
		&i.Instructions,
		&i.Hashtags,
		&i.GoogleAdsID,
		&i.AdsMonitoring,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, language, niche, location, primary_persona, tone, instructions, hashtags, google_ads_id, ads_monitoring, created_at, updated_at FROM tenants ORDER BY name
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Language,
			&i.Niche,
			&i.Location,
			&i.PrimaryPersona,
			&i.Tone,
			&i.Instructions,
			&i.Hashtags,
			&i.GoogleAdsID,
			&i.AdsMonitoring,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :exec
UPDATE tenants
SET name = $2, language = $3, niche = $4, location = $5,
    primary_persona = $6, tone = $7, instructions = $8,
    hashtags = $9, google_ads_id = $10, ads_monitoring = $11,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTenantParams struct {
	ID             string          `json:"id"`
	Name           string          `json:"name"`
	Language       string          `json:"language"`
	Niche          *string         `json:"niche"`
	Location       *string         `json:"location"`
	PrimaryPersona *string         `json:"primary_persona"`
	Tone           *string         `json:"tone"`
	Instructions   *string         `json:"instructions"`
	Hashtags       json.RawMessage `json:"hashtags"`
	GoogleAdsID    *string         `json:"google_ads_id"`
	AdsMonitoring  []byte          `json:"ads_monitoring"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) error {
	_, err := q.db.Exec(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Language,
		arg.Niche,
		arg.Location,
		arg.PrimaryPersona,
		arg.Tone,
		arg.Instructions,
		arg.Hashtags,
		arg.GoogleAdsID,
		arg.AdsMonitoring,
	)
	return err
}
