import { getDetailedCampaign } from '$lib/server/googleAdsDetailed';
import type { CampaignAdGroup } from '$lib/server/googleAdsDetailed';
import { getTenant } from '$lib/server/tenants';
import { error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';

function isValidSegment(s: string): boolean {
    return /^[a-z0-9][a-z0-9-_.]*$/i.test(s);
}

export const POST: RequestHandler = async ({ params, url }) => {
    if (!isValidSegment(params.client_id) || !isValidSegment(params.campaign_id)) {
        error(400, 'Invalid parameters');
    }

    const client = getTenant(params.client_id);

    if (!client) {
        error(404, 'Client not found');
    }

    const startDate = url.searchParams.get('startDate') || undefined;
    const endDate = url.searchParams.get('endDate') || undefined;

    const campaign = await getDetailedCampaign(client.google_ads_id ?? undefined, params.campaign_id, params.client_id, startDate, endDate);

    if (!campaign) {
        error(404, 'Live campaign not found in Google Ads');
    }

    const markdown = `# Campaign Report: ${campaign.name}
**ID:** ${campaign.id}
**Status:** ${campaign.status}
**Bidding Strategy:** ${campaign.strategy}

## Overall Metrics
- **Impressions:** ${campaign.metrics.impressions}
- **Search Impression Share:** ${campaign.metrics.searchImpressionShare}
- **Clicks:** ${campaign.metrics.clicks}
- **CTR:** ${campaign.metrics.ctr}
- **Interaction Rate:** ${campaign.metrics.interactionRate}
- **Cost:** $${campaign.metrics.cost}
- **Conversions:** ${campaign.metrics.conversions}
- **Conversion Value:** $${campaign.metrics.conversionsValue}
- **CPA (Cost per Conv):** $${campaign.metrics.cpa}
- **ROAS:** ${campaign.metrics.roas}

## Ad Groups Performance
${campaign.adGroups.map((ag: CampaignAdGroup) => `
### ${ag.name} (${ag.status})
- Impressions: ${ag.metrics.impressions}
- Clicks: ${ag.metrics.clicks}
- Cost: $${ag.metrics.cost}
- Conversions: ${ag.metrics.conversions}
`).join('\n')}

---
*Generated by Marketing AI Agent.*`;

    return new Response(markdown, {
        headers: {
            'Content-Type': 'text/markdown',
            'Content-Disposition': `attachment; filename="campaign_${campaign.id}.md"`
        }
    });
};